
export const English_Book = [
 {id:'1',book:'Genesis'},
 {id:'2',book:'Exodus'},
 {id:'3',book:'Leviticus'},
 {id:'4',book:'Numbers'},
 {id:'5',book:'Deuteronomy'},
 {id:'6',book:'Joshua'},
 {id:'8',book:'Ruth'},
 {id:'9',book:'1 Samuel'},
 {id:'10',book:'2 Samuel'},
 {id:'11',book:'1 Kings'},
 {id:'12',book:'2 Kings'},
 {id:'13',book:'1 Chronicles'},
 {id:'14',book:'2 Chronicles'},
 {id:'15',book:'Ezra'},
 {id:'16',book:'Nehemiah'},
 {id:'17',book:'Esther'},
 {id:'18',book:'Job'},
 {id:'19',book:'Psalm'},
 {id:'20',book:'Proverbs'},
 {id:'21',book:'Ecclesiastes'},
 {id:'22',book:'Songs of Solomon'},
 {id:'23',book:'Isaiah'},
 {id:'24',book:'Jeremiah'},
 {id:'25',book:'Lamentations'},
 {id:'26',book:'Ezekiel'},
 {id:'27',book:'Daniel'},
 {id:'28',book:'Hosea'},
 {id:'29',book:'Joel'},
 {id:'30',book:'Amos'},
 {id:'31',book:'Obadiah'},
 {id:'32',book:'Jonah'},
 {id:'33',book:'Micah'},
 {id:'34',book:'Nahum'},
 {id:'35',book:'Habakkuk'},
 {id:'36',book:'Zephaniah'},
 {id:'37',book:'Haggai'},
 {id:'38',book:'Zechariah'},
 {id:'39',book:'Malachi'},
 {id:'40',book:'Matthew'},
 {id:'41',book:'Mark'},
 {id:'42',book:'Luke'},
 {id:'43',book:'John'},
 {id:'44',book:'Acts'},
 {id:'45',book:'Romans'},
 {id:'46',book:'1 Corinthians'},
 {id:'47',book:'2 Corinthians'},
 {id:'48',book:'Galatians'},
 {id:'49',book:'Ephesians'},
 {id:'50',book:'Philippians'},
 {id:'51',book:'Colossians'},
 {id:'52',book:'1 Thessalonians'},
 {id:'53',book:'2 Thessalonians'},
 {id:'54',book:'1 Timothy'},
 {id:'55',book:'2 Timothy'},
 {id:'56',book:'Titus'},
 {id:'57',book:'Philemon'},
 {id:'58',book:'Hebrews'},
 {id:'59',book:'James'},
 {id:'60',book:'1 Peter'},
 {id:'61',book:'2 Peter'},
 {id:'62',book:'1 John'},
 {id:'63',book:'2 John'},
 {id:'64',book:'3 John'},
 {id:'65',book:'Jude'},
 {id:'66',book:'Revelation'},
]

export const French_Book = [
 {id:'1',book:'Genèse'},
 {id:'2',book:'Exode'},
 {id:'3',book:'Lévitique'},
 {id:'4',book:'Nombres'},
 {id:'5',book:'Deutéronome'},
 {id:'6',book:'Josué'},
 {id:'8',book:'Ruth'},
 {id:'9',book:'1 Samuel'},
 {id:'10',book:'2 Samuel'},
 {id:'11',book:'1 Rois'},
 {id:'12',book:'2 Rois'},
 {id:'13',book:'1 Chroniques'},
 {id:'14',book:'2 Chroniques'},
 {id:'15',book:'Esdras'},
 {id:'16',book:'Néhémie'},
 {id:'17',book:'Esther'},
 {id:'18',book:'Job'},
 {id:'19',book:'Psaumes'},
 {id:'20',book:'Proverbes'},
 {id:'21',book:'Ecclésiaste'},
 {id:'22',book:'Cantique des Cantiques'},
 {id:'23',book:'Ésaïe'},
 {id:'24',book:'Jérémie'},
 {id:'25',book:'Lamentations'},
 {id:'26',book:'Ézéchiel'},
 {id:'27',book:'Daniel'},
 {id:'28',book:'Osée'},
 {id:'29',book:'Joël'},
 {id:'30',book:'Amos'},
 {id:'31',book:'Abdias'},
 {id:'32',book:'Jonas'},
 {id:'33',book:'Michée'},
 {id:'34',book:'Nahum'},
 {id:'35',book:'Habacuc'},
 {id:'36',book:'Sophonie'},
 {id:'37',book:'Aggée'},
 {id:'38',book:'Zacharie'},
 {id:'39',book:'Malachie'},
 {id:'40',book:'Matthieu'},
 {id:'41',book:'Marc'},
 {id:'42',book:'Luc'},
 {id:'43',book:'Jean'},
 {id:'44',book:'Actes'},
 {id:'45',book:'Romains'},
 {id:'46',book:'1 Corinthiens'},
 {id:'47',book:'2 Corinthiens'},
 {id:'48',book:'Galates'},
 {id:'49',book:'Éphésiens'},
 {id:'50',book:'Philippiens'},
 {id:'51',book:'Colossiens'},
 {id:'52',book:'1 Thessaloniciens'},
 {id:'53',book:'2 Thessaloniciens'},
 {id:'54',book:'1 Timothée'},
 {id:'55',book:'2 Timothée'},
 {id:'56',book:'Tite'},
 {id:'57',book:'Philémon'},
 {id:'58',book:'Hébreux'},
 {id:'59',book:'Jacques'},
 {id:'60',book:'1 Pierre'},
 {id:'61',book:'2 Pierre '},
 {id:'62',book:'1 Jean'},
 {id:'63',book:'2 Jean'},
 {id:'64',book:'3 Jean'},
 {id:'65',book:'Jude'},
 {id:'66',book:'Apocalypse'},
]
 

 

 
 









 